server:
  port: 8899

spring:
  application:
    name: code-generator #指定服务名
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/backend_db?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver